### ISSUE TITLE
Custom CSS Styles · evanshultz/neater-bookmarks Wiki

### ISSUE THREAD

**Issue by tg-z** [tg-z/web-clip#311]
Custom CSS Styles · evanshultz/neater-bookmarks Wiki                                      

![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPAgMAAABGuH3ZAAAAAXNSR0IArs4c6QAAAAlQTFRF/2YA////AAAALA0mBgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAAEnMAABJzAYwiuQcAAAAHdElNRQfcCxUTCRv8+I/EAAAAMklEQVQI12NYtWrVCoapoaERDBMYGCSghAMLkBAQABIsDkCCkQHGAouBZeGKwXpBpgAAhtMRBKRIycIAAAAASUVORK5CYII=)
[![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAPBAMAAACB51W8AAAAAXNSR0IArs4c6QAAACRQTFRFAAEAAxx+JCYjYWNgho53kJKPy6Gio63Ys7Wysb3lyMnG/f/8AJKv4wAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfcBhsNKDWiRqoQAAAA2UlEQVQoz42SoQ7CMBCGL10w7CWWEAwzNRiwOEzD5DwvgSGoJVUoBAZFSGeWQZPSeznabutYtiX709b0y3/X/wowVSFW0vZ4iSMOq2hAGVgux2d98dl15UFmQMVr4zHwAAsFsMXMAJdltKKzYVACgTVAbA2RucYdaLZfDtSJhJgGPMPvHRk5QwKpvWvXvi5NjZ3pkeP1hDQoiaxAb9eAb0gtqDneULMW7DmWplb8gI19rOiC3R4VkCgsYW5T539gPx7lhmITFH4So4G7qM1kpoBC5DiqYvLn+QGXavuS25r9yAAAAABJRU5ErkJggg==)
](https://github.com/evanshultz/neater-bookmarks/commits/master.atom "https://github.com/evanshultz/neater-bookmarks/commits/master.atom")

[Skip to content](#start-of-content)

    ![](https://github.githubassets.com/images/search-key-slash.svg)

*   ![]()
    
    In this repository All GitHub ↵
    
    Jump to ↵
    

*   No suggested jump to results

*   ![]()
    
    In this repository All GitHub ↵
    
    Jump to ↵
    
*   ![]()
    
    In this repository All GitHub ↵
    
    Jump to ↵
    
*   ![](https://github.githubassets.com/images/spinners/octocat-spinner-128.gif)
    

[Dashboard](/dashboard) [Pull requests](https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3Atg-z+archived%3Afalse+sort%3Aupdated-desc) [Issues](https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3Atg-z+archived%3Afalse+sort%3Aupdated-desc) [Trending](/trending) [Explore](/explore)[![](https://avatars3.githubusercontent.com/u/47585455?s=60&v=4)
 tg-z](https://github.com/tg-z) 

 Sign out 

[evanshultz](/evanshultz) / [neater-bookmarks](/evanshultz/neater-bookmarks)

[New repository](/new) [Import repository](/new/import) [New gist](https://gist.github.com/) [New organization](/organizations/new)

This repository

[New issue](/evanshultz/neater-bookmarks/issues/new) [New project](/evanshultz/neater-bookmarks/projects/new)

 ![](https://avatars0.githubusercontent.com/u/47585455?s=40&v=4) [Signed in as **tg-z**](/tg-z)

![](https://github.githubassets.com/images/icons/emoji/octocat.png)

lost

### Edit status

 

![](https://github.githubassets.com/images/icons/emoji/octocat.png)

![](https://github.githubassets.com/images/icons/emoji/octocat.png)

  

Could not update your status, please try again.

80 remaining

#### Suggestions:

🌴

On vacation

🤒

Out sick

🏠

Working from home

🎯

Focusing

 Busy 

When others mention you, assign you, or request your review, GitHub will let them know that you have limited availability.

Clear status

Never

*   Never
    
    Keep this status until you clear your status or edit your status.
    

*   in 30 minutes
*   in 1 hour
*   in 4 hours
*   today
*   this week

Set status Clear status

[Your profile](/tg-z) [Your repositories](/tg-z?tab=repositories) [Your projects](/tg-z?tab=projects) [Your stars](/tg-z?tab=stars) [Your gists](https://gist.github.com/mine)

[Marketplace](/marketplace)

Feature preview

[Help](https://help.github.com) [Settings](/settings/profile)

 Sign out 

*         Watch   
    
    Notifications
    
    Not watching Be notified only when participating or @mentioned. Watch
    
    Releases only Be notified of new releases, and when participating or @mentioned. Unwatch releases
    
    Watching Be notified of all conversations. Unwatch
    
    Ignoring Never be notified. Stop ignoring
    
    [18](/evanshultz/neater-bookmarks/watchers)
    
*       Unstar  [180](/evanshultz/neater-bookmarks/stargazers) 
    
        Star  [180](/evanshultz/neater-bookmarks/stargazers) 
    
*      Fork
    
    [85](/evanshultz/neater-bookmarks/network/members)

[evanshultz](/evanshultz)/**[neater-bookmarks](/evanshultz/neater-bookmarks)** forked from [cheeaun/neat-bookmarks](/cheeaun/neat-bookmarks)
============================================================================================================================================

[Code  ](/evanshultz/neater-bookmarks)   [  Issues 64  ](https://github.com/evanshultz/neater-bookmarks/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)  [  Pull requests 10  ](https://github.com/evanshultz/neater-bookmarks/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) 

[Boards](#issue-sh-boards)

[Reports](#issue-sh-reports)

[Projects 0](/evanshultz/neater-bookmarks/projects) [Wiki](/evanshultz/neater-bookmarks/wiki) [Releases](/evanshultz/neater-bookmarks/releases) More [Compare](/evanshultz/neater-bookmarks/compare) [Dependencies](/evanshultz/neater-bookmarks/network/dependencies) [Commits](/evanshultz/neater-bookmarks/commits) [Branches](/evanshultz/neater-bookmarks/branches) [Security](https://github.com/evanshultz/neater-bookmarks/security/advisories) [Insights](https://github.com/evanshultz/neater-bookmarks/pulse)

[Code  ](/evanshultz/neater-bookmarks)   [ Issues 64  ](https://github.com/evanshultz/neater-bookmarks/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)   [ Pull requests 10  ](https://github.com/evanshultz/neater-bookmarks/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)   [ Projects 0  ](/evanshultz/neater-bookmarks/projects)   [ Wiki  ](/evanshultz/neater-bookmarks/wiki)  [ Security  ](/evanshultz/neater-bookmarks/security/advisories) [Pulse](/evanshultz/neater-bookmarks/pulse) 

Custom CSS Styles
=================

[Jump to bottom](#wiki-pages-box) [Edit](/evanshultz/neater-bookmarks/wiki/Custom-CSS-Styles/_edit) [New Page](/evanshultz/neater-bookmarks/wiki/_new)

Stefan Koshy edited this page on Sep 24 · [12 revisions](/evanshultz/neater-bookmarks/wiki/Custom-CSS-Styles/_history)

Simply copy and paste this code in the **Custom Styles** section of the Neater Bookmarks Options page.

Simpler theme (by [xendke](https://github.com/xendke)):

```css
input {
  outline: none;
}
img[src="folder.png"] {
  display: none;
}
#tree {
  padding: 5px 5px;
}
::-webkit-scrollbar {
  width: 6px;
}
::-webkit-scrollbar-track {
  background:transparent;
}
::-webkit-scrollbar-thumb {
  -webkit-border-radius: 10px;
  border-radius: 10px;
  background: #ccc;
  background: rgba(0,0,0,0.2); 
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0); 
}
::-webkit-scrollbar-thumb:window-inactive {
  background: rgba(255,0,0,0); 
}
@-webkit-keyframes blueFade {
  0% {
    background-color: transparent;
  }
  10%{
    background-color: #DCDCDC;
  }
  100% {
    background-color: transparent;
  }
}
#results ul li a:active,
#results ul li a.active,
#results ul li a:focus,
#tree ul li a:active,
#tree ul li span:active,
#tree ul li a.active,
#tree ul li span.active,
#tree ul li a:focus,
#tree ul li span:focus,
menu[type=context] command:focus{
  color: #fff;
  background-color: #585858;
  background-image: none;
  -webkit-box-shadow: 0 -1px #5594d2;	
  text-shadow: 0 0 rgba(255,255,255,.5), 0 1px rgba(0,0,0,.5);
  outline: 0;
}
```

Custom Google-style scrollbars in popup (by [evanshultz](https://github.com/evanshultz)):

```css
::-webkit-scrollbar {
  width: 9px;
  background: #eee;
}
::-webkit-scrollbar-thumb {
  background-color: rgba(0,0,0,0.2);
  border-top: 1px solid rgba(0,0,0,0.1);
  border-bottom: 1px solid rgba(0,0,0,0.07);
  border-left: 1px solid rgba(0,0,0,0.1);
}
```

Larger font size (by [cheeaun](https://gist.github.com/cheeaun)):

```css
body, #search input, #edit-dialog input {font-size: 14px;}
.dialog-text {font-size: 15px;}
```

Dark theme (by [skoshy](https://github.com/skoshy)):

```css
body {
  background: #333;
}
#search input {
  background: #555;
  border: 0;
  padding: 5px;
  color: #eee;
}
#search input::placeholder {
  color: #aaa;
}
#results ul li a, #tree ul li a, #tree ul li span {
  text-shadow: none;
  color: white;
}
#tree ul a img:not([src="folder.png"]) {
  background: #999;
  border: 1px solid #aaa;
  border-radius: 4px;
  transition: background ease-in-out 100ms;
}
#tree ul a:hover > img:not([src="folder.png"]),
#tree ul a:focus > img:not([src="folder.png"])
{
  background: #fff;
}
```

[Add a custom footer](/evanshultz/neater-bookmarks/wiki/_new?wiki%5Bname%5D=_Footer)

### Pages 8

*   **[Home](/evanshultz/neater-bookmarks/wiki)**
*   **[Custom CSS Styles](/evanshultz/neater-bookmarks/wiki/Custom-CSS-Styles)**
*   **[Custom icons](/evanshultz/neater-bookmarks/wiki/Custom-icons)**
*   **[Development Priority](/evanshultz/neater-bookmarks/wiki/Development-Priority)**
*   **[Load unpacked extension](/evanshultz/neater-bookmarks/wiki/Load-unpacked-extension)**
*   **[MY BM'S](/evanshultz/neater-bookmarks/wiki/MY-BM'S)**
*   **[Neater Bookmarks Testers](/evanshultz/neater-bookmarks/wiki/Neater-Bookmarks-Testers)**
*   **[Troubleshooting info](/evanshultz/neater-bookmarks/wiki/Troubleshooting-info)**

[Add a custom sidebar](/evanshultz/neater-bookmarks/wiki/_new?wiki%5Bname%5D=_Sidebar)

##### Clone this wiki locally

  

*   © 2019 GitHub, Inc.
*   [Terms](https://github.com/site/terms)
*   [Privacy](https://github.com/site/privacy)
*   [Security](https://github.com/security)
*   [Status](https://githubstatus.com/)
*   [Help](https://help.github.com)

[](https://github.com "GitHub")

*   [Contact GitHub](https://github.com/contact)
*   [Pricing](https://github.com/pricing)
*   [API](https://developer.github.com)
*   [Training](https://training.github.com)
*   [Blog](https://github.blog)
*   [About](https://github.com/about)

You can’t perform that action at this time.

You signed in with another tab or window. Reload to refresh your session. You signed out in another tab or window. Reload to refresh your session.

![](blob:https://github.com/f3a00a7c-7307-4efb-a49f-5c89caf94e7c)

Octotree

[](javascript:void(0))[](javascript:void(0))

Settings

GitHub access token

Hotkeys

 Open sidebar on hover

 Load entire tree at once

 Show in non-code pages

 Show file-specific icons

 Show pull request changes Note: maximum of 300 files 

Apply settings

Loving Octotree? You will love Octotree Pro even more. Octotree Pro is loaded with features that bring your productivity to the next level. [Learn more](https://www.octotree.io/?utm_source=lite&utm_medium=extension)

[Octotree and GitHub in dark mode](https://www.octotree.io/?utm_source=lite&utm_medium=extension&utm_content=Octotree and GitHub in dark mode)
