### ISSUE TITLE
Replicating a Tree table

### ISSUE THREAD

**Issue by tg-z** [tg-z/web-clip#520]
Replicating a Tree table                                            

![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPAgMAAABGuH3ZAAAAAXNSR0IArs4c6QAAAAlQTFRF/2YA////AAAALA0mBgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAAEnMAABJzAYwiuQcAAAAHdElNRQfcCxUTCRv8+I/EAAAAMklEQVQI12NYtWrVCoapoaERDBMYGCSghAMLkBAQABIsDkCCkQHGAouBZeGKwXpBpgAAhtMRBKRIycIAAAAASUVORK5CYII=)
[![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAPAgMAAAAOp6AcAAAAAXNSR0IArs4c6QAAAAxQTFRFAAAA/2YAiY55////S8IQBgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wLFRMROauDVnkAAAB7SURBVBjTpc8xDoAgDEBRLuXsKToaT0FMungfMLgz4CmMdygzC1G0yGIii/EPDM0LaYWo1Z6vdtFADtWj6ctwhKNfcTE26ehm8nHhodxAApKx3iifX3vL0AM6Y09NxDJlOUAHK2o2ihkVKbcwAiZNaSb25c9/e1Zvr3UBWOasaPHYnJwAAAAASUVORK5CYII=)
](http://maxdesign.com.au/feed/ "http://maxdesign.com.au/feed/") [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAPAgMAAAAOp6AcAAAAAXNSR0IArs4c6QAAAAxQTFRFAAAA/2YAiY55////S8IQBgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wLFRMROauDVnkAAAB7SURBVBjTpc8xDoAgDEBRLuXsKToaT0FMungfMLgz4CmMdygzC1G0yGIii/EPDM0LaYWo1Z6vdtFADtWj6ctwhKNfcTE26ehm8nHhodxAApKx3iifX3vL0AM6Y09NxDJlOUAHK2o2ihkVKbcwAiZNaSb25c9/e1Zvr3UBWOasaPHYnJwAAAAASUVORK5CYII=)
](http://maxdesign.com.au/comments/feed/ "http://maxdesign.com.au/comments/feed/") [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAPAgMAAAAOp6AcAAAAAXNSR0IArs4c6QAAAAxQTFRFAAAA/2YAiY55////S8IQBgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wLFRMROauDVnkAAAB7SURBVBjTpc8xDoAgDEBRLuXsKToaT0FMungfMLgz4CmMdygzC1G0yGIii/EPDM0LaYWo1Z6vdtFADtWj6ctwhKNfcTE26ehm8nHhodxAApKx3iifX3vL0AM6Y09NxDJlOUAHK2o2ihkVKbcwAiZNaSb25c9/e1Zvr3UBWOasaPHYnJwAAAAASUVORK5CYII=)
](http://maxdesign.com.au/maxdesign/xmlrpc.php?rsd "http://maxdesign.com.au/maxdesign/xmlrpc.php?rsd")

[Max Design](http://maxdesign.com.au/)

Exciting, engaging websites

*   [Home](http://maxdesign.com.au/)
*   [About](http://maxdesign.com.au/about/)
*   [News](http://maxdesign.com.au/category/news/)
*   [Articles](http://maxdesign.com.au/category/articles/)
*   [Training](http://maxdesign.com.au/training/)
*   [CSS](http://css.maxdesign.com.au)

Replicating a Tree table
========================

October 1, 2005 by [Russ Weakley](http://maxdesign.com.au/author/m74qg8x7mwuhu/)

### Aim

The aim is to replicate a graphic table tree using HTML. This was based on a request from a Web Standards Group member. Posted here in case it is of use to someone else.

### Graphic example of a table tree

![](http://maxdesign.com.au/maxdesign/wp-content/uploads/2015/04/table-tree01.gif)

### Screenshot of HTML example of a table tree

![](http://maxdesign.com.au/maxdesign/wp-content/uploads/2015/04/table-tree02.gif)

### HTML code

```markup
<table summary="folder contents for fly types">
	<thead>
		<tr>
			<th class="name">Name</th>
			<th class="location">Location</th>
			<th class="color">Color</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th colspan="3">House</th>
		</tr>
		<tr>
			<th class="start">Carrion Fly</th>
			<td>Worldwide</td>
			<td>gray</td>
		</tr>
		<tr>
			<th class="start">Office Fly</th>
			<td>California, Bay Area</td>
			<td>white</td>
		</tr>
		<tr>
			<th class="end">Common House Fly</th>
			<td></td>
			<td>brown</td>
		</tr>
		<tr>
			<th colspan="3">Horse</th>
		</tr>
		<tr>
			<th class="start">Horn Fly</th>
			<td>Kansas</td>
			<td>red</td>
		</tr>
		<tr>
			<th class="start">Face Fly</th>
			<td></td>
			<td>green</td>
		</tr>
		<tr class="end">
			<th class="end">Stable Fly</th>
			<td></td>
			<td>black</td>
		</tr>
	</tbody>
</table>

```

### CSS code

```css
body
{
	font-family: arial, helvetica, sans-serif;
}

table
{
	border-collapse: collapse;
	margin-bottom: 3em;
	font-size: 70%;
	line-height: 1.1;
}

tr:hover, td.start:hover, td.end:hover
{
	background: #FF9;
}

th, td
{
	padding: .3em .5em;
}

th
{
	font-weight: normal;
	text-align: left;
	background: url(tabletree-arrow.gif) no-repeat 2px 50%;
	padding-left: 15px;
}

th.name { width: 12em; }
th.location { width: 12em; }
th.color { width: 10em; }

thead th
{
	background: #c6ceda;
	border-color: #fff #fff #888 #fff;
	border-style: solid;
	border-width: 1px 1px 2px 1px;
	padding-left: .5em;
}

tbody th.start
{
	background: url(tabletree-dots.gif) 18px 54% no-repeat;
	padding-left: 26px;
}

tbody th.end
{
	background: url(tabletree-dots2.gif) 18px 54% no-repeat;
	padding-left: 26px;
}

```

Filed Under: [Articles](http://maxdesign.com.au/category/articles/)

[Contact us](/contact-us/)

*   [Facebook](https://www.facebook.com/russweakley)
*   [Github](https://github.com/russmaxdesign)
*   [Linkedin](https://www.linkedin.com/in/russweakley)
*   [Twitter](https://twitter.com/russmaxdesign)

© 2016 Max Design

Copyright © 2019 · [Parallax Pro Theme](http://my.studiopress.com/themes/parallax/) on [Genesis Framework](https://www.studiopress.com/) · [WordPress](https://wordpress.org/) · [Log in](http://maxdesign.com.au/maxdesign/wp-login.php)

![](blob:http://maxdesign.com.au/cda8b653-6891-4cb7-a365-01491d6d7968) 
 http://maxdesign.com.au/articles/tree-table/
